// Opcode table for 6502 CPU
// Maps each opcode byte to its instruction information

use crate::cpu::addressing::AddressingMode;
use crate::cpu::Cpu;

/// Information about a single opcode
#[derive(Clone, Copy)]
pub struct OpcodeInfo {
    /// The opcode byte value
    pub opcode: u8,
    /// Mnemonic name of the instruction
    pub mnemonic: &'static str,
    /// Number of bytes including the opcode
    pub bytes: u8,
    /// Base number of cycles (may be increased by page crossing)
    pub cycles: u8,
    /// Additional cycle if page boundary is crossed
    pub page_cycle: bool,
    /// Addressing mode used by this instruction
    pub mode: AddressingMode,
}

impl OpcodeInfo {
    const fn new(
        opcode: u8,
        mnemonic: &'static str,
        bytes: u8,
        cycles: u8,
        page_cycle: bool,
        mode: AddressingMode,
    ) -> Self {
        Self {
            opcode,
            mnemonic,
            bytes,
            cycles,
            page_cycle,
            mode,
        }
    }
}

/// Complete 6502 opcode table (all 256 opcodes)
/// Official opcodes are implemented, unofficial opcodes are marked as "???"
pub const OPCODE_TABLE: [OpcodeInfo; 256] = [
    // 0x00-0x0F
    OpcodeInfo::new(0x00, "BRK", 1, 7, false, AddressingMode::Implied),
    OpcodeInfo::new(0x01, "ORA", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0x02, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x03, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x04, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x05, "ORA", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x06, "ASL", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x07, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x08, "PHP", 1, 3, false, AddressingMode::Implied),
    OpcodeInfo::new(0x09, "ORA", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0x0A, "ASL", 1, 2, false, AddressingMode::Accumulator),
    OpcodeInfo::new(0x0B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x0C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x0D, "ORA", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x0E, "ASL", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x0F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x10-0x1F
    OpcodeInfo::new(0x10, "BPL", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0x11, "ORA", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0x12, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x13, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x14, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x15, "ORA", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x16, "ASL", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x17, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x18, "CLC", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x19, "ORA", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0x1A, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x1B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x1C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x1D, "ORA", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x1E, "ASL", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x1F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x20-0x2F
    OpcodeInfo::new(0x20, "JSR", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x21, "AND", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0x22, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x23, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x24, "BIT", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x25, "AND", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x26, "ROL", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x27, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x28, "PLP", 1, 4, false, AddressingMode::Implied),
    OpcodeInfo::new(0x29, "AND", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0x2A, "ROL", 1, 2, false, AddressingMode::Accumulator),
    OpcodeInfo::new(0x2B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x2C, "BIT", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x2D, "AND", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x2E, "ROL", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x2F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x30-0x3F
    OpcodeInfo::new(0x30, "BMI", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0x31, "AND", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0x32, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x33, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x34, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x35, "AND", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x36, "ROL", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x37, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x38, "SEC", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x39, "AND", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0x3A, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x3B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x3C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x3D, "AND", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x3E, "ROL", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x3F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x40-0x4F
    OpcodeInfo::new(0x40, "RTI", 1, 6, false, AddressingMode::Implied),
    OpcodeInfo::new(0x41, "EOR", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0x42, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x43, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x44, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x45, "EOR", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x46, "LSR", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x47, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x48, "PHA", 1, 3, false, AddressingMode::Implied),
    OpcodeInfo::new(0x49, "EOR", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0x4A, "LSR", 1, 2, false, AddressingMode::Accumulator),
    OpcodeInfo::new(0x4B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x4C, "JMP", 3, 3, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x4D, "EOR", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x4E, "LSR", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x4F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x50-0x5F
    OpcodeInfo::new(0x50, "BVC", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0x51, "EOR", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0x52, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x53, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x54, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x55, "EOR", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x56, "LSR", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x57, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x58, "CLI", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x59, "EOR", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0x5A, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x5B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x5C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x5D, "EOR", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x5E, "LSR", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x5F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x60-0x6F
    OpcodeInfo::new(0x60, "RTS", 1, 6, false, AddressingMode::Implied),
    OpcodeInfo::new(0x61, "ADC", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0x62, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x63, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x64, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x65, "ADC", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x66, "ROR", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x67, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x68, "PLA", 1, 4, false, AddressingMode::Implied),
    OpcodeInfo::new(0x69, "ADC", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0x6A, "ROR", 1, 2, false, AddressingMode::Accumulator),
    OpcodeInfo::new(0x6B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x6C, "JMP", 3, 5, false, AddressingMode::Indirect),
    OpcodeInfo::new(0x6D, "ADC", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x6E, "ROR", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x6F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x70-0x7F
    OpcodeInfo::new(0x70, "BVS", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0x71, "ADC", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0x72, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x73, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x74, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x75, "ADC", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x76, "ROR", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x77, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x78, "SEI", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x79, "ADC", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0x7A, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x7B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x7C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x7D, "ADC", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x7E, "ROR", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x7F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x80-0x8F
    OpcodeInfo::new(0x80, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x81, "STA", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0x82, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x83, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x84, "STY", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x85, "STA", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x86, "STX", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0x87, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x88, "DEY", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x89, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x8A, "TXA", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x8B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x8C, "STY", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x8D, "STA", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x8E, "STX", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0x8F, "???", 1, 2, false, AddressingMode::Implied),
    // 0x90-0x9F
    OpcodeInfo::new(0x90, "BCC", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0x91, "STA", 2, 6, false, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0x92, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x93, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x94, "STY", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x95, "STA", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0x96, "STX", 2, 4, false, AddressingMode::ZeroPageY),
    OpcodeInfo::new(0x97, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x98, "TYA", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x99, "STA", 3, 5, false, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0x9A, "TXS", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x9B, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x9C, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x9D, "STA", 3, 5, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0x9E, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0x9F, "???", 1, 2, false, AddressingMode::Implied),
    // 0xA0-0xAF
    OpcodeInfo::new(0xA0, "LDY", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xA1, "LDA", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0xA2, "LDX", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xA3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xA4, "LDY", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xA5, "LDA", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xA6, "LDX", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xA7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xA8, "TAY", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xA9, "LDA", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xAA, "TAX", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xAB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xAC, "LDY", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xAD, "LDA", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xAE, "LDX", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xAF, "???", 1, 2, false, AddressingMode::Implied),
    // 0xB0-0xBF
    OpcodeInfo::new(0xB0, "BCS", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0xB1, "LDA", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0xB2, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xB3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xB4, "LDY", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xB5, "LDA", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xB6, "LDX", 2, 4, false, AddressingMode::ZeroPageY),
    OpcodeInfo::new(0xB7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xB8, "CLV", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xB9, "LDA", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0xBA, "TSX", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xBB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xBC, "LDY", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xBD, "LDA", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xBE, "LDX", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0xBF, "???", 1, 2, false, AddressingMode::Implied),
    // 0xC0-0xCF
    OpcodeInfo::new(0xC0, "CPY", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xC1, "CMP", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0xC2, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xC3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xC4, "CPY", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xC5, "CMP", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xC6, "DEC", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xC7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xC8, "INY", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xC9, "CMP", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xCA, "DEX", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xCB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xCC, "CPY", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xCD, "CMP", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xCE, "DEC", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xCF, "???", 1, 2, false, AddressingMode::Implied),
    // 0xD0-0xDF
    OpcodeInfo::new(0xD0, "BNE", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0xD1, "CMP", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0xD2, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xD3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xD4, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xD5, "CMP", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xD6, "DEC", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xD7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xD8, "CLD", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xD9, "CMP", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0xDA, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xDB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xDC, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xDD, "CMP", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xDE, "DEC", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xDF, "???", 1, 2, false, AddressingMode::Implied),
    // 0xE0-0xEF
    OpcodeInfo::new(0xE0, "CPX", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xE1, "SBC", 2, 6, false, AddressingMode::IndexedIndirect),
    OpcodeInfo::new(0xE2, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xE3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xE4, "CPX", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xE5, "SBC", 2, 3, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xE6, "INC", 2, 5, false, AddressingMode::ZeroPage),
    OpcodeInfo::new(0xE7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xE8, "INX", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xE9, "SBC", 2, 2, false, AddressingMode::Immediate),
    OpcodeInfo::new(0xEA, "NOP", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xEB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xEC, "CPX", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xED, "SBC", 3, 4, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xEE, "INC", 3, 6, false, AddressingMode::Absolute),
    OpcodeInfo::new(0xEF, "???", 1, 2, false, AddressingMode::Implied),
    // 0xF0-0xFF
    OpcodeInfo::new(0xF0, "BEQ", 2, 2, true, AddressingMode::Relative),
    OpcodeInfo::new(0xF1, "SBC", 2, 5, true, AddressingMode::IndirectIndexed),
    OpcodeInfo::new(0xF2, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xF3, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xF4, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xF5, "SBC", 2, 4, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xF6, "INC", 2, 6, false, AddressingMode::ZeroPageX),
    OpcodeInfo::new(0xF7, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xF8, "SED", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xF9, "SBC", 3, 4, true, AddressingMode::AbsoluteY),
    OpcodeInfo::new(0xFA, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xFB, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xFC, "???", 1, 2, false, AddressingMode::Implied),
    OpcodeInfo::new(0xFD, "SBC", 3, 4, true, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xFE, "INC", 3, 7, false, AddressingMode::AbsoluteX),
    OpcodeInfo::new(0xFF, "???", 1, 2, false, AddressingMode::Implied),
];

impl Cpu {
    /// Get opcode information for a given opcode byte
    pub fn get_opcode_info(opcode: u8) -> &'static OpcodeInfo {
        &OPCODE_TABLE[opcode as usize]
    }
}
